/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef payment_CONSTANTS_H
#define payment_CONSTANTS_H

#include "payment_types.h"

namespace accpayment_thrift {

class paymentConstants {
 public:
  paymentConstants();

};

extern const paymentConstants g_payment_constants;

} // namespace

#endif
