/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef PaymentChannel_H
#define PaymentChannel_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "payment_channel_types.h"

namespace payment_channel {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class PaymentChannelIf {
 public:
  virtual ~PaymentChannelIf() {}
  virtual void query(std::string& _return, const std::string& logid, const std::string& request) = 0;
  virtual void pay(std::string& _return, const std::string& logid, const std::string& request) = 0;
};

class PaymentChannelIfFactory {
 public:
  typedef PaymentChannelIf Handler;

  virtual ~PaymentChannelIfFactory() {}

  virtual PaymentChannelIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(PaymentChannelIf* /* handler */) = 0;
};

class PaymentChannelIfSingletonFactory : virtual public PaymentChannelIfFactory {
 public:
  PaymentChannelIfSingletonFactory(const boost::shared_ptr<PaymentChannelIf>& iface) : iface_(iface) {}
  virtual ~PaymentChannelIfSingletonFactory() {}

  virtual PaymentChannelIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(PaymentChannelIf* /* handler */) {}

 protected:
  boost::shared_ptr<PaymentChannelIf> iface_;
};

class PaymentChannelNull : virtual public PaymentChannelIf {
 public:
  virtual ~PaymentChannelNull() {}
  void query(std::string& /* _return */, const std::string& /* logid */, const std::string& /* request */) {
    return;
  }
  void pay(std::string& /* _return */, const std::string& /* logid */, const std::string& /* request */) {
    return;
  }
};

typedef struct _PaymentChannel_query_args__isset {
  _PaymentChannel_query_args__isset() : logid(false), request(false) {}
  bool logid :1;
  bool request :1;
} _PaymentChannel_query_args__isset;

class PaymentChannel_query_args {
 public:

  PaymentChannel_query_args(const PaymentChannel_query_args&);
  PaymentChannel_query_args& operator=(const PaymentChannel_query_args&);
  PaymentChannel_query_args() : logid(), request() {
  }

  virtual ~PaymentChannel_query_args() throw();
  std::string logid;
  std::string request;

  _PaymentChannel_query_args__isset __isset;

  void __set_logid(const std::string& val);

  void __set_request(const std::string& val);

  bool operator == (const PaymentChannel_query_args & rhs) const
  {
    if (!(logid == rhs.logid))
      return false;
    if (!(request == rhs.request))
      return false;
    return true;
  }
  bool operator != (const PaymentChannel_query_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PaymentChannel_query_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class PaymentChannel_query_pargs {
 public:


  virtual ~PaymentChannel_query_pargs() throw();
  const std::string* logid;
  const std::string* request;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _PaymentChannel_query_result__isset {
  _PaymentChannel_query_result__isset() : success(false) {}
  bool success :1;
} _PaymentChannel_query_result__isset;

class PaymentChannel_query_result {
 public:

  PaymentChannel_query_result(const PaymentChannel_query_result&);
  PaymentChannel_query_result& operator=(const PaymentChannel_query_result&);
  PaymentChannel_query_result() : success() {
  }

  virtual ~PaymentChannel_query_result() throw();
  std::string success;

  _PaymentChannel_query_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const PaymentChannel_query_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const PaymentChannel_query_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PaymentChannel_query_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _PaymentChannel_query_presult__isset {
  _PaymentChannel_query_presult__isset() : success(false) {}
  bool success :1;
} _PaymentChannel_query_presult__isset;

class PaymentChannel_query_presult {
 public:


  virtual ~PaymentChannel_query_presult() throw();
  std::string* success;

  _PaymentChannel_query_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _PaymentChannel_pay_args__isset {
  _PaymentChannel_pay_args__isset() : logid(false), request(false) {}
  bool logid :1;
  bool request :1;
} _PaymentChannel_pay_args__isset;

class PaymentChannel_pay_args {
 public:

  PaymentChannel_pay_args(const PaymentChannel_pay_args&);
  PaymentChannel_pay_args& operator=(const PaymentChannel_pay_args&);
  PaymentChannel_pay_args() : logid(), request() {
  }

  virtual ~PaymentChannel_pay_args() throw();
  std::string logid;
  std::string request;

  _PaymentChannel_pay_args__isset __isset;

  void __set_logid(const std::string& val);

  void __set_request(const std::string& val);

  bool operator == (const PaymentChannel_pay_args & rhs) const
  {
    if (!(logid == rhs.logid))
      return false;
    if (!(request == rhs.request))
      return false;
    return true;
  }
  bool operator != (const PaymentChannel_pay_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PaymentChannel_pay_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class PaymentChannel_pay_pargs {
 public:


  virtual ~PaymentChannel_pay_pargs() throw();
  const std::string* logid;
  const std::string* request;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _PaymentChannel_pay_result__isset {
  _PaymentChannel_pay_result__isset() : success(false) {}
  bool success :1;
} _PaymentChannel_pay_result__isset;

class PaymentChannel_pay_result {
 public:

  PaymentChannel_pay_result(const PaymentChannel_pay_result&);
  PaymentChannel_pay_result& operator=(const PaymentChannel_pay_result&);
  PaymentChannel_pay_result() : success() {
  }

  virtual ~PaymentChannel_pay_result() throw();
  std::string success;

  _PaymentChannel_pay_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const PaymentChannel_pay_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const PaymentChannel_pay_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PaymentChannel_pay_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _PaymentChannel_pay_presult__isset {
  _PaymentChannel_pay_presult__isset() : success(false) {}
  bool success :1;
} _PaymentChannel_pay_presult__isset;

class PaymentChannel_pay_presult {
 public:


  virtual ~PaymentChannel_pay_presult() throw();
  std::string* success;

  _PaymentChannel_pay_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class PaymentChannelClient : virtual public PaymentChannelIf {
 public:
  PaymentChannelClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  PaymentChannelClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void query(std::string& _return, const std::string& logid, const std::string& request);
  void send_query(const std::string& logid, const std::string& request);
  void recv_query(std::string& _return);
  void pay(std::string& _return, const std::string& logid, const std::string& request);
  void send_pay(const std::string& logid, const std::string& request);
  void recv_pay(std::string& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class PaymentChannelProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<PaymentChannelIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (PaymentChannelProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_query(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_pay(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  PaymentChannelProcessor(boost::shared_ptr<PaymentChannelIf> iface) :
    iface_(iface) {
    processMap_["query"] = &PaymentChannelProcessor::process_query;
    processMap_["pay"] = &PaymentChannelProcessor::process_pay;
  }

  virtual ~PaymentChannelProcessor() {}
};

class PaymentChannelProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  PaymentChannelProcessorFactory(const ::boost::shared_ptr< PaymentChannelIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< PaymentChannelIfFactory > handlerFactory_;
};

class PaymentChannelMultiface : virtual public PaymentChannelIf {
 public:
  PaymentChannelMultiface(std::vector<boost::shared_ptr<PaymentChannelIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~PaymentChannelMultiface() {}
 protected:
  std::vector<boost::shared_ptr<PaymentChannelIf> > ifaces_;
  PaymentChannelMultiface() {}
  void add(boost::shared_ptr<PaymentChannelIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void query(std::string& _return, const std::string& logid, const std::string& request) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->query(_return, logid, request);
    }
    ifaces_[i]->query(_return, logid, request);
    return;
  }

  void pay(std::string& _return, const std::string& logid, const std::string& request) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->pay(_return, logid, request);
    }
    ifaces_[i]->pay(_return, logid, request);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class PaymentChannelConcurrentClient : virtual public PaymentChannelIf {
 public:
  PaymentChannelConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  PaymentChannelConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void query(std::string& _return, const std::string& logid, const std::string& request);
  int32_t send_query(const std::string& logid, const std::string& request);
  void recv_query(std::string& _return, const int32_t seqid);
  void pay(std::string& _return, const std::string& logid, const std::string& request);
  int32_t send_pay(const std::string& logid, const std::string& request);
  void recv_pay(std::string& _return, const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

} // namespace

#endif
