/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef payment_channel_CONSTANTS_H
#define payment_channel_CONSTANTS_H

#include "payment_channel_types.h"

namespace payment_channel {

class payment_channelConstants {
 public:
  payment_channelConstants();

};

extern const payment_channelConstants g_payment_channel_constants;

} // namespace

#endif
