/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "payment_channel_constants.h"

namespace payment_channel {

const payment_channelConstants g_payment_channel_constants;

payment_channelConstants::payment_channelConstants() {
}

} // namespace

