/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef CupsChannel_H
#define CupsChannel_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "test_zk_s_types.h"

namespace payment_channel {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class CupsChannelIf {
 public:
  virtual ~CupsChannelIf() {}
  virtual void DoTrans(std::string& _return, const std::string& logid, const std::string& request) = 0;
};

class CupsChannelIfFactory {
 public:
  typedef CupsChannelIf Handler;

  virtual ~CupsChannelIfFactory() {}

  virtual CupsChannelIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(CupsChannelIf* /* handler */) = 0;
};

class CupsChannelIfSingletonFactory : virtual public CupsChannelIfFactory {
 public:
  CupsChannelIfSingletonFactory(const boost::shared_ptr<CupsChannelIf>& iface) : iface_(iface) {}
  virtual ~CupsChannelIfSingletonFactory() {}

  virtual CupsChannelIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(CupsChannelIf* /* handler */) {}

 protected:
  boost::shared_ptr<CupsChannelIf> iface_;
};

class CupsChannelNull : virtual public CupsChannelIf {
 public:
  virtual ~CupsChannelNull() {}
  void DoTrans(std::string& /* _return */, const std::string& /* logid */, const std::string& /* request */) {
    return;
  }
};

typedef struct _CupsChannel_DoTrans_args__isset {
  _CupsChannel_DoTrans_args__isset() : logid(false), request(false) {}
  bool logid :1;
  bool request :1;
} _CupsChannel_DoTrans_args__isset;

class CupsChannel_DoTrans_args {
 public:

  CupsChannel_DoTrans_args(const CupsChannel_DoTrans_args&);
  CupsChannel_DoTrans_args& operator=(const CupsChannel_DoTrans_args&);
  CupsChannel_DoTrans_args() : logid(), request() {
  }

  virtual ~CupsChannel_DoTrans_args() throw();
  std::string logid;
  std::string request;

  _CupsChannel_DoTrans_args__isset __isset;

  void __set_logid(const std::string& val);

  void __set_request(const std::string& val);

  bool operator == (const CupsChannel_DoTrans_args & rhs) const
  {
    if (!(logid == rhs.logid))
      return false;
    if (!(request == rhs.request))
      return false;
    return true;
  }
  bool operator != (const CupsChannel_DoTrans_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CupsChannel_DoTrans_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class CupsChannel_DoTrans_pargs {
 public:


  virtual ~CupsChannel_DoTrans_pargs() throw();
  const std::string* logid;
  const std::string* request;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _CupsChannel_DoTrans_result__isset {
  _CupsChannel_DoTrans_result__isset() : success(false) {}
  bool success :1;
} _CupsChannel_DoTrans_result__isset;

class CupsChannel_DoTrans_result {
 public:

  CupsChannel_DoTrans_result(const CupsChannel_DoTrans_result&);
  CupsChannel_DoTrans_result& operator=(const CupsChannel_DoTrans_result&);
  CupsChannel_DoTrans_result() : success() {
  }

  virtual ~CupsChannel_DoTrans_result() throw();
  std::string success;

  _CupsChannel_DoTrans_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const CupsChannel_DoTrans_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const CupsChannel_DoTrans_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CupsChannel_DoTrans_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _CupsChannel_DoTrans_presult__isset {
  _CupsChannel_DoTrans_presult__isset() : success(false) {}
  bool success :1;
} _CupsChannel_DoTrans_presult__isset;

class CupsChannel_DoTrans_presult {
 public:


  virtual ~CupsChannel_DoTrans_presult() throw();
  std::string* success;

  _CupsChannel_DoTrans_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class CupsChannelClient : virtual public CupsChannelIf {
 public:
  CupsChannelClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  CupsChannelClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void DoTrans(std::string& _return, const std::string& logid, const std::string& request);
  void send_DoTrans(const std::string& logid, const std::string& request);
  void recv_DoTrans(std::string& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class CupsChannelProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<CupsChannelIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (CupsChannelProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_DoTrans(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  CupsChannelProcessor(boost::shared_ptr<CupsChannelIf> iface) :
    iface_(iface) {
    processMap_["DoTrans"] = &CupsChannelProcessor::process_DoTrans;
  }

  virtual ~CupsChannelProcessor() {}
};

class CupsChannelProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  CupsChannelProcessorFactory(const ::boost::shared_ptr< CupsChannelIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< CupsChannelIfFactory > handlerFactory_;
};

class CupsChannelMultiface : virtual public CupsChannelIf {
 public:
  CupsChannelMultiface(std::vector<boost::shared_ptr<CupsChannelIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~CupsChannelMultiface() {}
 protected:
  std::vector<boost::shared_ptr<CupsChannelIf> > ifaces_;
  CupsChannelMultiface() {}
  void add(boost::shared_ptr<CupsChannelIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void DoTrans(std::string& _return, const std::string& logid, const std::string& request) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->DoTrans(_return, logid, request);
    }
    ifaces_[i]->DoTrans(_return, logid, request);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class CupsChannelConcurrentClient : virtual public CupsChannelIf {
 public:
  CupsChannelConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  CupsChannelConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void DoTrans(std::string& _return, const std::string& logid, const std::string& request);
  int32_t send_DoTrans(const std::string& logid, const std::string& request);
  void recv_DoTrans(std::string& _return, const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

} // namespace

#endif
