/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef test_zk_s_CONSTANTS_H
#define test_zk_s_CONSTANTS_H

#include "test_zk_s_types.h"

namespace payment_channel {

class test_zk_sConstants {
 public:
  test_zk_sConstants();

};

extern const test_zk_sConstants g_test_zk_s_constants;

} // namespace

#endif
