/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "threads_constants.h"

namespace threads_thrift {

const threadsConstants g_threads_constants;

threadsConstants::threadsConstants() {
}

} // namespace

