/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef threads_CONSTANTS_H
#define threads_CONSTANTS_H

#include "threads_types.h"

namespace threads_thrift {

class threadsConstants {
 public:
  threadsConstants();

};

extern const threadsConstants g_threads_constants;

} // namespace

#endif
