/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "test_zk_s_constants.h"

namespace payment_channel {

const test_zk_sConstants g_test_zk_s_constants;

test_zk_sConstants::test_zk_sConstants() {
}

} // namespace

